---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: calculator
  name: joke-factor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joke-factor
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: joke-factor
        tier: backend
    spec:
      containers:
      - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: calculadora-api-db-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calculadora-api-db-secret
              key: db-password
        - name: DB_HOST
          value: "__DB_HOST__"
        - name: DB_NAME
          value: "mydb"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: signoz-otel-collector.signoz.svc.cluster.local:4317
        image: __IMAGEM__
        imagePullPolicy: IfNotPresent
        name: joke-factor
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          failureThreshold: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          failureThreshold: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: calculator
  name: joke-factor
  labels:
    app: joke-factor
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: joke-factor
    tier: backend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-joke-factor
  namespace: calculator
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: joke-factor
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
