name: "APPS - CI/CD"

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      environment:
        type: string
        required: true
      app-name:
        type: string
        required: true
      app-path:
        type: string
        required: true
      ecr-repository:
        type: string
        required: true
      eks-cluster-name:
        type: string
        required: true
      app-namespace-kubernetes:
        type: string
        required: true
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      CERTIFICATE_ARN:
        required: false

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.app-path }}
          file: ./${{ inputs.app-path }}/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ inputs.environment }}-${{ github.run_number }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Substituir variáveis nos manifestos
        uses: sandersaares-actions/expand-tokens@master
        env:
          USUARIO_BANCO: ${{ secrets.DB_USER }}
          SENHA_BANCO: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          IMAGEM: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ inputs.environment }}-${{ github.run_number }}
        with:
          path: ${{ inputs.app-path }}
          recursive: true

      - name: Deploy to EKS
        working-directory: ./${{ inputs.app-path }}
        run: |
          aws eks update-kubeconfig --name "${{ inputs.eks-cluster-name }}" --region ${{ inputs.aws-region }}

          echo -e "\nArquivo de manifesto que será aplicado:\n"
          cat ./k8s/manifesto.yaml

          kubectl apply -f ./k8s/manifesto.yaml
