name: "INFRA - Terraform Workflow"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: true
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Validate
        run: make ci-validate

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Read destroy configuration
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.${{ inputs.environment }}' ./destroy_config.json)"
          echo "destroy=$DESTROY" >> $GITHUB_OUTPUT

      - name: Terraform Destroy
        if: steps.read-destroy-config.outputs.destroy == 'true'
        run: |
          make destroy-plan ENV=${{ inputs.environment }}
          make destroy ENV=${{ inputs.environment }}

      - name: Terraform Plan
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: make plan ENV=${{ inputs.environment }}

      - name: Terraform Apply
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: make apply ENV=${{ inputs.environment }}
